/**
 * YouTube transcript fetcher with language priority and error handling.
 */

import { YoutubeTranscript } from "youtube-transcript";
import { join } from "path";
import type { TranscriptData, TranscriptError, TranscriptSegment } from "./types.js";
import { TRANSCRIPTS_DIR, TRANSCRIPT_FETCH_DELAY, TRANSCRIPT_LANGUAGE_PRIORITY } from "./config.js";
import { getLogger, sleep, nowIso, saveJson, loadJson } from "./utils.js";

interface RawTranscriptItem {
  text: string;
  offset: number;
  duration: number;
  lang?: string;
}

/**
 * Fetch transcript for a video with language priority.
 */
export async function fetchTranscript(
  videoId: string,
  videoTitle: string
): Promise<TranscriptData | TranscriptError> {
  const log = getLogger();

  const languageNames: Record<string, string> = {
    hi: "Hindi",
    en: "English",
  };

  // Helper to convert raw items to our format
  function toResult(
    transcript: RawTranscriptItem[],
    langCode: string,
    isAuto: boolean
  ): TranscriptData {
    const segments: TranscriptSegment[] = transcript.map((item) => ({
      text: item.text,
      start: item.offset / 1000,
      duration: item.duration / 1000,
    }));
    return {
      videoId,
      videoTitle,
      language: langCode,
      languageName: languageNames[langCode] || langCode,
      isAutoGenerated: isAuto,
      fetchedAt: nowIso(),
      segments,
      fullText: segments.map((s) => s.text).join(" "),
    };
  }

  // Try each language in priority order
  for (const [langCode, isAuto] of TRANSCRIPT_LANGUAGE_PRIORITY) {
    try {
      const transcript = await YoutubeTranscript.fetchTranscript(videoId, {
        lang: langCode,
      });
      if (transcript && transcript.length > 0) {
        log.info(`Fetched transcript for ${videoId} (${langCode}${isAuto ? " auto" : ""})`);
        return toResult(transcript, langCode, isAuto);
      }
    } catch (error: unknown) {
      const err = error as { message?: string };
      log.debug(`No ${langCode} transcript for ${videoId}: ${err.message}`);
    }
  }

  // Fallback: let YouTube pick whatever CC/transcript is available
  try {
    const transcript = await YoutubeTranscript.fetchTranscript(videoId);
    if (transcript && transcript.length > 0) {
      const detectedLang = (transcript[0] as RawTranscriptItem & { lang?: string }).lang ?? "unknown";
      log.info(`Fetched CC fallback for ${videoId} (lang: ${detectedLang})`);
      return toResult(transcript, detectedLang, true);
    }
  } catch (error: unknown) {
    const err = error as { message?: string };
    log.debug(`No CC fallback for ${videoId}: ${err.message}`);
  }

  // No transcript or CC available in any form
  log.warn(`No transcript available for ${videoId}`);

  return {
    videoId,
    videoTitle,
    error: "no_transcript_available",
    fetchedAt: nowIso(),
  };
}

/**
 * Get the transcript file path for a video.
 */
export function getTranscriptPath(videoId: string): string {
  return join(TRANSCRIPTS_DIR, `${videoId}.json`);
}

/**
 * Check if transcript already exists for a video.
 */
export function transcriptExists(videoId: string): boolean {
  const path = getTranscriptPath(videoId);
  const data = loadJson<TranscriptData | TranscriptError>(path);
  return data !== null;
}

/**
 * Save transcript data to file.
 */
export function saveTranscript(data: TranscriptData | TranscriptError): void {
  const path = getTranscriptPath(data.videoId);
  saveJson(path, data);
}

/**
 * Load transcript data from file.
 */
export function loadTranscript(videoId: string): TranscriptData | TranscriptError | null {
  const path = getTranscriptPath(videoId);
  return loadJson<TranscriptData | TranscriptError>(path);
}

/**
 * Check if a transcript result is an error.
 */
export function isTranscriptError(
  data: TranscriptData | TranscriptError
): data is TranscriptError {
  return "error" in data;
}

/**
 * Fetch and save transcripts for multiple videos.
 */
export async function fetchTranscripts(
  videos: Array<{ id: string; title: string }>,
  skipExisting: boolean = true,
  onProgress?: (completed: number, total: number, videoId: string, success: boolean) => void
): Promise<{ success: string[]; failed: string[] }> {
  const log = getLogger();
  const success: string[] = [];
  const failed: string[] = [];

  log.info(`Fetching transcripts for ${videos.length} videos`);

  for (let i = 0; i < videos.length; i++) {
    const video = videos[i];

    // Skip if already exists
    if (skipExisting && transcriptExists(video.id)) {
      log.debug(`Skipping existing transcript: ${video.id}`);
      const existing = loadTranscript(video.id);
      if (existing && !isTranscriptError(existing)) {
        success.push(video.id);
      } else {
        failed.push(video.id);
      }
      onProgress?.(i + 1, videos.length, video.id, !isTranscriptError(existing!));
      continue;
    }

    try {
      const result = await fetchTranscript(video.id, video.title);
      saveTranscript(result);

      if (isTranscriptError(result)) {
        failed.push(video.id);
        onProgress?.(i + 1, videos.length, video.id, false);
      } else {
        success.push(video.id);
        onProgress?.(i + 1, videos.length, video.id, true);
      }
    } catch (error: unknown) {
      const err = error as { message?: string };
      log.error(`Failed to fetch transcript for ${video.id}: ${err.message}`);

      // Save error marker
      const errorData: TranscriptError = {
        videoId: video.id,
        videoTitle: video.title,
        error: err.message || "unknown_error",
        fetchedAt: nowIso(),
      };
      saveTranscript(errorData);
      failed.push(video.id);
      onProgress?.(i + 1, videos.length, video.id, false);
    }

    // Rate limit
    if (i < videos.length - 1) {
      await sleep(TRANSCRIPT_FETCH_DELAY);
    }
  }

  log.info(`Transcripts complete: ${success.length} success, ${failed.length} failed`);

  return { success, failed };
}
