/**
 * YouTube transcript/CC fetcher using yt-dlp.
 *
 * Uses yt-dlp with --cookies-from-browser chrome to bypass YouTube's PO token
 * requirement for auto-generated captions. Falls back through language priority.
 *
 * Requires: pip3 install yt-dlp  (already installed)
 */

import { execSync } from "child_process";
import { mkdirSync, existsSync, readFileSync, readdirSync, rmSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { tmpdir } from "os";
import type { TranscriptData, TranscriptError, TranscriptSegment } from "./types.js";
import { TRANSCRIPTS_DIR, TRANSCRIPT_FETCH_DELAY } from "./config.js";
import { getLogger, sleep, nowIso, saveJson, loadJson } from "./utils.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Language priority: prefer Hindi (channel language), then English variants
const LANG_PRIORITY = ["hi", "en", "en-IN", "en-GB", "en-US"];

const LANG_NAMES: Record<string, string> = {
  hi: "Hindi",
  en: "English",
  "en-IN": "English (India)",
  "en-GB": "English (UK)",
  "en-US": "English (US)",
};

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8: string }>;
}

interface Json3Data {
  events?: Json3Event[];
}

/**
 * Parse a yt-dlp JSON3 subtitle file into segments + full text.
 */
function parseJson3(filePath: string): { segments: TranscriptSegment[]; fullText: string } {
  const raw = readFileSync(filePath, "utf-8");
  const data = JSON.parse(raw) as Json3Data;
  const events = data.events ?? [];

  const segments: TranscriptSegment[] = events
    .filter((e) => e.segs && e.segs.length > 0)
    .map((e) => ({
      text: e.segs!.map((s) => s.utf8).join("").replace(/\n/g, " ").trim(),
      start: (e.tStartMs ?? 0) / 1000,
      duration: (e.dDurationMs ?? 0) / 1000,
    }))
    .filter((s) => s.text.length > 0);

  const fullText = segments.map((s) => s.text).join(" ");
  return { segments, fullText };
}

/**
 * Detect the language of a downloaded subtitle file from its filename.
 * yt-dlp names files: VIDEO_ID.LANG.json3
 */
function detectLang(filename: string, videoId: string): string {
  const prefix = `${videoId}.`;
  const suffix = ".json3";
  if (filename.startsWith(prefix) && filename.endsWith(suffix)) {
    return filename.slice(prefix.length, -suffix.length);
  }
  return "unknown";
}

/**
 * Fetch CC/transcript for one video using yt-dlp.
 */
export async function fetchTranscript(
  videoId: string,
  videoTitle: string
): Promise<TranscriptData | TranscriptError> {
  const log = getLogger();

  const tmpDir = join(tmpdir(), `yt-cc-${videoId}`);
  mkdirSync(tmpDir, { recursive: true });

  try {
    const subLangs = LANG_PRIORITY.join(",");
    const cmd = [
      "python3 -m yt_dlp",
      "--cookies-from-browser chrome",
      "--skip-download",
      "--write-auto-subs",
      "--write-subs",
      `--sub-langs "${subLangs}"`,
      "--sub-format json3",
      "--no-warnings",
      "--quiet",
      `-o "${tmpDir}/%(id)s"`,
      `"https://www.youtube.com/watch?v=${videoId}"`,
    ].join(" ");

    execSync(cmd, { stdio: "pipe", timeout: 60_000 });

    // Find downloaded subtitle files
    const files = readdirSync(tmpDir).filter((f) => f.endsWith(".json3"));

    if (files.length === 0) {
      log.warn(`No CC found for ${videoId}`);
      return { videoId, videoTitle, error: "no_transcript_available", fetchedAt: nowIso() };
    }

    // Pick best language in priority order
    let bestFile: string | null = null;
    let bestLang = "unknown";

    for (const lang of LANG_PRIORITY) {
      const match = files.find((f) => {
        const detected = detectLang(f, videoId);
        return detected === lang || detected === `${lang}-orig`;
      });
      if (match) {
        bestFile = join(tmpDir, match);
        bestLang = lang;
        break;
      }
    }

    // Fallback: just take the first file
    if (!bestFile) {
      bestFile = join(tmpDir, files[0]);
      bestLang = detectLang(files[0], videoId);
    }

    const { segments, fullText } = parseJson3(bestFile);

    if (fullText.trim().length === 0) {
      return { videoId, videoTitle, error: "empty_transcript", fetchedAt: nowIso() };
    }

    log.info(`CC fetched for ${videoId} (${bestLang}, ${segments.length} segments, ${fullText.length} chars)`);

    return {
      videoId,
      videoTitle,
      language: bestLang,
      languageName: LANG_NAMES[bestLang] ?? bestLang,
      isAutoGenerated: true,
      fetchedAt: nowIso(),
      segments,
      fullText,
    };
  } catch (error: unknown) {
    const err = error as { message?: string; stderr?: Buffer };
    const msg = err.stderr?.toString() || err.message || "unknown_error";
    log.warn(`yt-dlp failed for ${videoId}: ${msg.slice(0, 120)}`);
    return { videoId, videoTitle, error: msg.slice(0, 200), fetchedAt: nowIso() };
  } finally {
    // Clean up temp files
    try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
}

// ── Rest of the file unchanged ─────────────────────────────────────────────

export function getTranscriptPath(videoId: string): string {
  return join(TRANSCRIPTS_DIR, `${videoId}.json`);
}

export function transcriptExists(videoId: string): boolean {
  const path = getTranscriptPath(videoId);
  const data = loadJson<TranscriptData | TranscriptError>(path);
  return data !== null;
}

export function saveTranscript(data: TranscriptData | TranscriptError): void {
  saveJson(getTranscriptPath(data.videoId), data);
}

export function loadTranscript(videoId: string): TranscriptData | TranscriptError | null {
  return loadJson<TranscriptData | TranscriptError>(getTranscriptPath(videoId));
}

export function isTranscriptError(
  data: TranscriptData | TranscriptError
): data is TranscriptError {
  return "error" in data;
}

export async function fetchTranscripts(
  videos: Array<{ id: string; title: string }>,
  skipExisting: boolean = true,
  onProgress?: (completed: number, total: number, videoId: string, success: boolean) => void
): Promise<{ success: string[]; failed: string[] }> {
  const log = getLogger();
  const success: string[] = [];
  const failed: string[] = [];

  log.info(`Fetching CC for ${videos.length} videos via yt-dlp`);

  for (let i = 0; i < videos.length; i++) {
    const video = videos[i];

    if (skipExisting && transcriptExists(video.id)) {
      log.debug(`Skipping existing: ${video.id}`);
      const existing = loadTranscript(video.id);
      const ok = !isTranscriptError(existing!);
      (ok ? success : failed).push(video.id);
      onProgress?.(i + 1, videos.length, video.id, ok);
      continue;
    }

    const result = await fetchTranscript(video.id, video.title);
    saveTranscript(result);

    const ok = !isTranscriptError(result);
    (ok ? success : failed).push(video.id);
    onProgress?.(i + 1, videos.length, video.id, ok);

    if (i < videos.length - 1) {
      await sleep(TRANSCRIPT_FETCH_DELAY);
    }
  }

  log.info(`CC complete: ${success.length} ok, ${failed.length} failed`);
  return { success, failed };
}
