/**
 * Type definitions for Street Food Map pipeline.
 */

export interface ChannelInfo {
  id: string;
  title: string;
  description: string;
  customUrl?: string;
  publishedAt: string;
  thumbnailUrl?: string;
  subscriberCount?: string;
  videoCount?: string;
  viewCount?: string;
  uploadsPlaylistId?: string;
}

export interface PlaylistInfo {
  id: string;
  title: string;
  description: string;
  videoCount: number;
  publishedAt: string;
  thumbnailUrl?: string;
}

export interface PlaylistsData {
  channelId: string;
  channelHandle: string;
  channelTitle: string;
  fetchedAt: string;
  playlists: PlaylistInfo[];
}

export interface VideoInfo {
  id: string;
  title: string;
  description: string;
  publishedAt: string;
  thumbnailUrl?: string;
  channelId?: string;
  channelTitle?: string;
  tags?: string[];
  duration?: string;
  viewCount?: string;
  likeCount?: string;
  commentCount?: string;
  playlists?: Array<{ id: string; title: string }>;
}

export interface VideosData {
  fetchedAt: string;
  totalVideos: number;
  videos: VideoInfo[];
}

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptData {
  videoId: string;
  videoTitle: string;
  language: string;
  languageName: string;
  isAutoGenerated: boolean;
  fetchedAt: string;
  segments: TranscriptSegment[];
  fullText: string;
}

export interface TranscriptError {
  videoId: string;
  videoTitle: string;
  error: string;
  fetchedAt: string;
}

export interface Progress {
  lastRun: string | null;
  channelHandle: string | null;
  channelId: string | null;
  playlistsFetched: boolean;
  videosFetched: boolean;
  transcriptsCompleted: string[];
  transcriptsFailed: string[];
  quotaUsed: number;
}

export interface ScraperOptions {
  channel: string;
  step?: "playlists" | "videos" | "transcripts";
  resume?: boolean;
  dryRun?: boolean;
  verbose?: boolean;
  limit?: number;
  city?: string;
}
